### ISSUE TITLE
product recommendations for guests

### ISSUE THREAD

**Issue by mch0lic** [gorse-io/gorse#419]
**Is your feature request related to a problem? Please describe.**
Demo only covers recommendation to logged in users, but typical ecommerce site could benefit from recommendations to guests by recommending products similar to one currently viewed or based on other products guest has in cart.

**Describe the solution you'd like**

- Create a solution with REST API exposed to provide recommendations that does not require user registration.
- Update project documentation with basic example how gorse could be used for product recommendation within ecommerce.

**Describe alternatives you've considered**
Commercial solutions for product recommendations (from basic to ML).

**Comment by zhenghaoz** [comment]
I think there could be an API like this:

```bash
$ curl -X POST http://localhost::8087/api/session/recommend  \
       -H "Content-Type: application/json"  \
       -d '[{ "FeedbackType": "star", "UserId": "user1", "ItemId": "item1", "Timestamp": "2022-02-24" }]'

[
 "item4",
 "item5",
 "item6"
]
```

- The input data is a list of feedback from a session (by guest).
- The recommendation is generated based on given items.

There has been an item-based recommendation method:

https://github.com/gorse-io/gorse/blob/8a50a86476677f7c773a39f25bb9f44872937d95/server/rest.go#L812-L861

And its unit test:

https://github.com/gorse-io/gorse/blob/8a50a86476677f7c773a39f25bb9f44872937d95/server/rest_test.go#L1074-L1184

In the new API, just read feedback from input data rather than the database.
